- name: variables from prompt
  Hosts: localhost
  vars_promt:
  - name: USERNAME
    prompt: Please enter the user name
    private: false #user can see what they entering
  - name: PASSWORD
    PROMPT: please enter the password
    private: true #user can't see what they entering
  tasks:
    name: print the variables
    ansible.builtin.debug:
      msg: "Username: {{USERNAME}} and Password: {{PASSWORD}}"