- name: variable preferences
  hosts: localhost
  vars_prompt:
  - name: Name
    prompt: Please provide your name
    private: false
  - name: wishes
    prompt: Please give your wishes
    private: false
  vars_files:
  - variables.yaml
  vars:
    Name: vamsi from play
    wishes: morning from play
  tasks:
  - name: variable check
    vars:
      Name: vamsi from play
      wishes: morning from play
    ansible.builtin.debug:
      msg: "Hi {{Name}}, good {{wishes}}"

