- name: loops
  hosts: localhost
  tasks:
  - name: print persons
    ansible.builtin.debug:
      msg: "Hello {{item}}" #item is a default keyword in ansible
    loop:
    - vamsi
    - sai
    - krishna
    